const randomEndpoint = () => {
    const limit = Math.floor(Math.random() * 118);
    let atomicNumber = Math.floor(Math.random() * 118);
    while (atomicNumber === 0) {
        atomicNumber = Math.floor(Math.random() * 118);
    }

    let block = Math.floor(Math.random() * 11);
    while (block === 0) {
        block = Math.floor(Math.random() * 11);
    }

    const blocks = [
        "nonmetal",
        "alkali metal",
        "alkaline earth metal",
        "metal",
        "metalloid",
        "transition metal",
        "post-transition metal",
        "lanthanoid",
        "actinoid",
        "halogen",
        "noble gas",
    ];

    let bondingType = Math.floor(Math.random() * 4);
    while (bondingType === 0) {
        bondingType = Math.floor(Math.random() * 4);
    }

    const bondingTypes = ["diatomic", "atomic", "metallic", "covalent network"];

    const names = [
        "Hydrogen",
        "Helium",
        "Lithium",
        "Beryllium",
        "Boron",
        "Carbon",
        "Nitrogen",
        "Oxygen",
        "Fluorine",
        "Neon",
        "Sodium",
        "Magnesium",
        "Aluminum",
        "Silicon",
        "Phosphorus",
        "Sulfur",
        "Chlorine",
        "Argon",
        "Potassium",
        "Calcium",
        "Scandium",
        "Titanium",
        "Vanadium",
        "Chromium",
        "Manganese",
        "Iron",
        "Cobalt",
        "Nickel",
        "Copper",
        "Zinc",
        "Gallium",
        "Germanium",
        "Arsenic",
        "Selenium",
        "Bromine",
        "Krypton",
        "Rubidium",
        "Strontium",
        "Yttrium",
        "Zirconium",
        "Niobium",
        "Molybdenum",
        "Technetium",
        "Ruthenium",
        "Rhodium",
        "Palladium",
        "Silver",
        "Cadmium",
        "Indium",
        "Tin",
        "Antimony",
        "Tellurium",
        "Iodine",
        "Xenon",
        "Cesium",
        "Barium",
        "Lanthanum",
        "Cerium",
        "Praseodymium",
        "Neodymium",
        "Promethium",
        "Samarium",
        "Europium",
        "Gadolinium",
        "Terbium",
        "Dysprosium",
        "Holmium",
        "Erbium",
        "Thulium",
        "Ytterbium",
        "Lutetium",
        "Hafnium",
        "Tantalum",
        "Tungsten",
        "Rhenium",
        "Osmium",
        "Iridium",
        "Platinum",
        "Gold",
        "Mercury",
        "Thallium",
        "Lead",
        "Bismuth",
        "Polonium",
        "Astatine",
        "Radon",
        "Francium",
        "Radium",
        "Actinium",
        "Thorium",
        "Protactinium",
        "Uranium",
        "Neptunium",
        "Plutonium",
        "Americium",
        "Curium",
        "Berkelium",
        "Californium",
        "Einsteinium",
        "Fermium",
        "Mendelevium",
        "Nobelium",
        "Lawrencium",
        "Rutherfordium",
        "Dubnium",
        "Seaborgium",
        "Bohrium",
        "Hassium",
        "Meitnerium",
        "Darmstadtium",
        "Roentgenium",
        "Copernicium",
        "Nihonium",
        "Flerovium",
        "Moscovium",
        "Livermorium",
        "Tennessine",
        "Oganesson",
    ];

    const states = ["gas", "solid", "liquid"];

    let state = Math.floor(Math.random() * 3);
    while (state === 0) {
        state = Math.floor(Math.random() * 3);
    }

    const symbols = [
        "H",
        "He",
        "Li",
        "Be",
        "B",
        "C",
        "N",
        "O",
        "F",
        "Ne",
        "Na",
        "Mg",
        "Al",
        "Si",
        "P",
        "S",
        "Cl",
        "Ar",
        "K",
        "Ca",
        "Sc",
        "Ti",
        "V",
        "Cr",
        "Mn",
        "Fe",
        "Co",
        "Ni",
        "Cu",
        "Zn",
        "Ga",
        "Ge",
        "As",
        "Se",
        "Br",
        "Kr",
        "Rb",
        "Sr",
        "Y",
        "Zr",
        "Nb",
        "Mo",
        "Tc",
        "Ru",
        "Rh",
        "Pd",
        "Ag",
        "Cd",
        "In",
        "Sn",
        "Sb",
        "Te",
        "I",
        "Xe",
        "Cs",
        "Ba",
        "La",
        "Ce",
        "Pr",
        "Nd",
        "Pm",
        "Sm",
        "Eu",
        "Gd",
        "Tb",
        "Dy",
        "Ho",
        "Er",
        "Tm",
        "Yb",
        "Lu",
        "Hf",
        "Ta",
        "W",
        "Re",
        "Os",
        "Ir",
        "Pt",
        "Au",
        "Hg",
        "Tl",
        "Pb",
        "Bi",
        "Po",
        "At",
        "Rn",
        "Fr",
        "Ra",
        "Ac",
        "Th",
        "Pa",
        "U",
        "Np",
        "Pu",
        "Am",
        "Cm",
        "Bk",
        "Cf",
        "Es",
        "Fm",
        "Md",
        "No",
        "Lr",
        "Rf",
        "Db",
        "Sg",
        "Bh",
        "Hs",
        "Mt",
        "Ds",
        "Rg",
        "Cn",
        "Nh",
        "Fl",
        "Mc",
        "Lv",
        "Ts",
        "Og",
    ];

    const endpoints: any = {
        1: `/api/elements?limit=${limit}`,
        2: `api/elements/atomicNumber/${atomicNumber}`,
        3: `api/elements/block/${blocks[block - 1]}?limit=${limit}`,
        4: `api/elements/bondingType/${bondingTypes[bondingType - 1]}?limit=${limit}`,
        5: `api/elements/name/${names[atomicNumber - 1]}`,
        6: `api/elements/state/${states[state - 1]}?limit=${limit}`,
        7: `api/elements/symbol/${symbols[atomicNumber - 1].toLowerCase()}`,
    };

    let random = Math.floor(Math.random() * 7);
    while (random === 0) {
        random = Math.floor(Math.random() * 7);
    }

    return `https://elements.apis.lol/${endpoints[random]}`;
};

export default randomEndpoint;
